mkdir -p /home/nginx/upload/tvimg/jstx0000
mkdir -p /home/nginx/upload/tvimg/channel
mkdir -p /home/nginx/upload/tvapk/sys
mkdir -p /home/nginx/upload/tvimg/appIcon
mkdir -p /home/nginx/upload/tvapk/appVersion
mkdir -p /home/nginx/upload/tvimg/bitmatrix
mkdir -p /home/nginx/upload/tvimg/focus
mkdir -p /home/nginx/upload/tvimg/recommend
mkdir -p /home/nginx/upload/tvimg/cast
mkdir -p /home/nginx/upload/tvimg/device
mkdir -p /home/nginx/upload/tvimg/weathericon
mkdir -p /home/nginx/upload/tvimg/weatherwallpaper